name: Python Checks - mypy

on:
  push:
    branches: [ "main" ]
  pull_request: null

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run type checker (mypy)
      run: |
        mypy --install-types --non-interactive --ignore-missing-imports --disable-error-code no-any-return .
